import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/general/Header";
import Footer from "@/components/general/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="bg-[#e0e5ec]">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#e0e5ec] min-h-screen flex flex-col`}
      >
        <Header />
        <main className="flex-1 flex flex-col justify-center items-center bg-[#e0e5ec]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
